package br.com.lojacalhas.telas;

import java.sql.*;
import br.com.lojacalhas.dal.ModuloConexao;
import java.awt.HeadlessException;
import java.util.Arrays;
import javax.swing.JOptionPane;

public class TelaLogin extends javax.swing.JFrame {

    Connection conn = null; //chamando o objeto que criamos no moduloConexão.
    PreparedStatement pst = null; // executa códigos sql em java.
    ResultSet rs = null; //exibe o resultado das consultas (query)
    
    

   

    public TelaLogin() {
        initComponents();
        conn = ModuloConexao.getConexao(); //chamamos o método criado para tentar a conexão
        System.out.println(conn); //Se tudo ocorrer bem, irá aparecer a String de conexão. 
        if (conn == null) {
         JOptionPane.showMessageDialog(null, "Sem conexão com o banco de dados. Favor entrar em contato com o suporte.");

        } 

    }
    
     public void logar() {
    /* Código abaixo serve para acessar o usuario e senha que for digitado, e fazer
       a consulta(query) no banco de dados. Se a query for correspondida, executa 
       a tomada de decisão, onde irá abrir a TelaPrincipal. 
    */
    String sql = "select * from tbusuarios where login=? and senha=?";
    try {
        pst = conn.prepareStatement(sql);
        pst.setString(1, txtUsuario.getText());

        // Obtém a senha de forma segura
        char[] senhaArray = pwdSenha.getPassword(); // Usando getPassword()
        pst.setString(2, new String(senhaArray)); // Convertendo senha para String
        
        // a linha abaixo executa a Query
        rs = pst.executeQuery();

        if (rs.next()) {
            // Uma observação: foi criada também uma tomada de decisão-Se o perfil for admin, o mesmo terá acesso completo ao sistema, diferente do perfil user.
            String perfil = rs.getString(6);
            if (perfil.equals("admin")) {
                TelaPrincipal1 tela = new TelaPrincipal1();
                tela.setVisible(true);
                TelaPrincipal1.menuCadUsu.setEnabled(true);
                TelaPrincipal1.menuRel.setEnabled(true);
                String usuario = rs.getString(2);
                TelaPrincipal1.lblUsuario.setText("Administrador, " + usuario);

                this.dispose();
            } else {
                TelaPrincipal1 tela = new TelaPrincipal1();
                tela.setVisible(true);
                String usuario = rs.getString(2);
                TelaPrincipal1.lblUsuario.setText(usuario);

                this.dispose();
                conn.close();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Usuário e/ou senha inválidos.");
        }

    } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(null, e);
    } finally {
        // Limpa o array de senha da memória para maior segurança
        Arrays.fill(pwdSenha.getPassword(), '0');
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        btnLogar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pwdSenha = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login de Usuário");
        setBounds(new java.awt.Rectangle(450, 450, 450, 450));
        setPreferredSize(new java.awt.Dimension(0, 0));
        setResizable(false);

        btnLogar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/consulta.png"))); // NOI18N
        btnLogar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255)));
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(135, 206, 250));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Usuário");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtUsuario.setPreferredSize(new java.awt.Dimension(55, 21));

        pwdSenha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setBackground(new java.awt.Color(135, 206, 250));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Senha");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calha (3).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(448, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
        logar();

    }//GEN-LAST:event_btnLogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField pwdSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
